### PR TITLE
Hide the install button entirely for incompatible versions in listing pages

### LINKED ISSUE #6119: Hide the install button for incompatible add-ons entirely in search/browse
From https://github.com/mozilla/addons-server/issues/5277#issuecomment-318074010

Hide the install button for incompatible add-ons entirely in search/browse/homepage and instead, show an expanded compatibility explanation and a link to the All Versions page.

### LINKED ISSUE #6150: Don't hide the install button for compatible add-ons while displaying disabled buttons
### Describe the problem and steps to reproduce it:
1. Load https://addons.mozilla.org/en-US/firefox/extensions/?sort=featured
2. Notice the install buttons for listed add-ons

### What happened?
For compatible add-ons, the install button is only visible on mouse-over whereas the disabled buttons are grayed out and are always shown.

### What did you expect to happen?
- Call-to-Action buttons for compatible add-ons are clearly visible
- When install buttons are missing, it may confuse the user into thinking that the add-on is incompatible

### Anything else we should know?
screenshot 2017-08-10 13 57 59

### PR DESCRIPTION
**Pull request by diox**
Also show "download anyway" button when incompatible (it was already displayed when showing the "Only with Firefox" button, this makes it available to every incompatible situation)

Fix #6119 
Fix #6150

### CODE REVIEW

File: static/js/zamboni/buttons.js [hunk 1]
```diff
@@ -186,6 +186,9 @@ var installButton = function() {
         var opts = $.extend({addWarning: true}, options);
             warn = opts.addWarning ? addWarning : _.identity;
 
+        $('#downloadAnyway').attr('href',escape_($button.filter(':visible').attr('href')));
```
Comment (EnTeQuAk) [inline static/js/zamboni/buttons.js]: whitespace after comma? I know this is just copied but you touched it so you're responsible 😇
