### PR TITLE
Fix up theme search templating

### LINKED ISSUE #1755: HTML tags visible in Editor Tools->Themes page after a blank search
Steps to reproduce:
1. Log in to AMO-stage with an admin account https://addons.allizom.org/
2. Go to Editor Tools - Themes https://addons.allizom.org/en-US/editors/themes
3. Go to any queue and make a blank search

**Expected results:**
All themes (searched theme) are listed or a "no results.." message is displayed. 

**Actual results:**
The search does not work. 

Notes/Issues:
HTML tags are visible in Updates queue. (in AMO-dev html tags are visible in every Theme queue after a search)
Verified on FF44(Win 7). Issue is reproducing in AMO-stage and AMO-dev.
Screencast for this issues: http://screencast.com/t/gDjxcpTDbuW

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #1755

### CODE REVIEW

File: static/js/zamboni/themes_review_templates.js [hunk 1]
```diff
@@ -60,17 +62,23 @@ _.template(`
...
 var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
 with(obj||{}){
-__p+='\n<script type="text/template" id="queue-search-row-template">\n  <tr class="addon-row">\n    <td class="app-name">\n      <span class="addon-id">'+
+__p+='\n <tr class="addon-row">\n    <td class="app-name">\n      <span class="addon-id">'+
 ((__t=( id ))==null?'':__t)+
 '</span>\n      <a href="'+
 ((__t=( review_url ))==null?'':__t)+
-'"><%- name %></a>\n    </td>\n    <td><a href="'+
+'">'+
+((__t=( name ))==null?'':_.escape(__t))+
```
Comment (tofumatt) [inline static/js/zamboni/themes_review_templates.js]: This is a bit gnarly to look at, some whitespace would be nice :smile:

File: static/js/zamboni/themes_review_templates.js [hunk 2]
```diff
@@ -60,17 +62,23 @@ _.template(`
...
+'</a>\n    </td>\n    <td>\n      ';
+if (typeof reviewer !== "undefined") {
+__p+='\n        <a href="'+
 ((__t=( reviewer ))==null?'':__t)+
 '">'+
 ((__t=( reviewer ))==null?'':__t)+
-'</a></td>\n    <td>'+
+'</a>\n      ';
+}
+__p+='\n    </td>\n    <td>'+
```
Comment (tofumatt) [inline static/js/zamboni/themes_review_templates.js]: Is all the whitespace in these strings needed?

File: static/js/zamboni/themes_review_templates.js [hunk 3]
```diff
@@ -43,16 +43,18 @@ return __p;
...
-<script type="text/template" id="queue-search-row-template">
   <tr class="addon-row">
     <td class="app-name">
       <span class="addon-id"><%= id %></span>
       <a href="<%= review_url %>"><%- name %></a>
     </td>
-    <td><a href="<%= reviewer %>"><%= reviewer %></a></td>
+    <td>
+      <% if (typeof reviewer !== "undefined") { %>
+        <a href="<%= reviewer %>"><%= reviewer %></a>
```
Comment (tofumatt) [inline static/js/zamboni/themes_review_templates.js]: I'll assume `reviewer` doesn't need escaping.

**Comment by tofumatt** [comment]
r+wc

File: static/js/zamboni/themes_review_templates.js (hunk 1 above)
Comment (muffinresearch) [inline static/js/zamboni/themes_review_templates.js]: It's generated code.

Comment (tofumatt) [inline static/js/zamboni/themes_review_templates.js]: Okay, cool. I figured, but I wasn’t sure. Ignore my comments then! :-)

File: static/js/zamboni/themes_review_templates.js (hunk 2 above)
Comment (muffinresearch) [inline static/js/zamboni/themes_review_templates.js]: It's a compiled template.

File: static/js/zamboni/themes_review_templates.js (hunk 3 above)
Comment (muffinresearch) [inline static/js/zamboni/themes_review_templates.js]: Hmm, yeah I wondered that too - I'm not sure exactly what reviewer is. Especially since it's used for the url too.

File: static/js/zamboni/themes_review_templates.js (hunk 1 above)
Comment (muffinresearch) [inline static/js/zamboni/themes_review_templates.js]: I promise I don't write code that looks like that normally. :)

File: static/js/zamboni/themes_review_templates.js (hunk 3 above)
Comment (muffinresearch) [inline static/js/zamboni/themes_review_templates.js]: Ok I managed to find something. The reviewer looks to be an email address. The link is totally borked and doesn't work. 

Also the data is broken somehow because the reviewer's email address is against the wrong result :/

Comment (muffinresearch) [inline static/js/zamboni/themes_review_templates.js]: I'll remove the link add escaping and see how that looks.

**Comment by tofumatt** [comment]
r+
