### PR TITLE
Make sure we only support file-syntax aliases for SyntaxHighlighter that are installed.

### LINKED ISSUE #4552: Filebrowser incorrectly shows line contents as "undefined"
### Describe the problem and steps to reproduce it:
* Go to https://addons.mozilla.org/en-US/firefox/files/compare/582238...566147/file/diffworker.diff
* See lots of "undefined" lines.

### What happened?
Aside from the fact that including this file was accidental, it does actually have readable content. Maybe it is because it is a patch file?

### What did you expect to happen?
The file contents should correctly be displayed.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes #4552 

Apparently we removed some brushes in our last cleanup of our SyntaxHighlighter library so this kinda broke with that.

Before:

screenshot from 2017-02-06 12-03-48

After:

screenshot from 2017-02-06 12-37-52

Not testable by QA but in case someone activates a brush (add it to the list of syntaxes supported) that is not installed:

screenshot from 2017-02-06 18-40-17

### CODE REVIEW

File: static/js/zamboni/files.js [hunk 1]
```diff
@@ -112,6 +112,34 @@ var Highlighter = {
...
+                }
+
+                for (var i = 0, l = aliases.length; i < l; i++) {
+                    brushes[aliases[i]] = discoveredBrush;
+                }
+            }
+
+            if (discoveredBrushes[brushes[brush]] == null) {
+                window.alert(format(
+                    'Could not find brush for: {0}. The output can be broken, please be careful!',
```
Comment (wagnerand) [inline static/js/zamboni/files.js]: Can we make this a little bit less technical, like
`File content not supported. The output can be broken, please be careful!` ? I'm fine with something else, I just don't think reviewers will know what a "brush" is, especially in this context.

File: src/olympia/files/helpers.py [hunk 2]
```diff
@@ -33,6 +33,21 @@
 LOCKED = 'locked'
 LOCKED_TIMEOUT = 60 * 5
 
+SYNTAX_HIGHLIGHTER_ALIAS_MAPPING = {
+    'xul': 'xml',
+    'rdf': 'xml',
+    'jsm': 'js',
+    'json': 'js',
```
Comment (wagnerand) [inline src/olympia/files/helpers.py]: I know this was in the old code as well, but do we really need it? Iiuc https://github.com/syntaxhighlighter/brush-javascript/blob/master/brush.js#L43 indicates that `json` does not need to be mapped.

Or are we even using the built-in JavaScript brush ourselves? https://github.com/mozilla/addons-server/blob/master/static/js/zamboni/files.js#L230-L254 defines our own JS brush, extending from the built-in one. Maybe we have to add `json` as an alias there?

File: src/olympia/files/helpers.py [hunk 3]
```diff
@@ -33,6 +33,21 @@
...
+    'htm': 'html'
+}
+
+# See settings.MINIFY_BUNDLES['css']['zamboni/files'] for more details
```
Comment (EnTeQuAk) [inline src/olympia/files/helpers.py]: hah! super fail on my side, nice find

File: src/olympia/files/helpers.py (hunk 2 above)
Comment (EnTeQuAk) [inline src/olympia/files/helpers.py]: True, I'll look into that. Yeah, I didn't touch any of that yet, we might be able to clean this up even more. If that's alright for everyone I'd do that in a separate pull request though to keep this separated.

File: static/js/zamboni/files.js (hunk 1 above)
Comment (EnTeQuAk) [inline static/js/zamboni/files.js]: I like your suggestion, I'll maybe go with ’File content not supported. The output can be broken, please be careful and report an issue immediately!’ - since, if that alert ever happens someone added or removed something from the python mapping without taking care of the javascript-side of things so the "report an issue" part is kinda important imho?

File: src/olympia/files/helpers.py (hunk 2 above)
Comment (wagnerand) [inline src/olympia/files/helpers.py]: Wfm.

File: static/js/zamboni/files.js (hunk 1 above)
Comment (wagnerand) [inline static/js/zamboni/files.js]: Good idea! But then we should also say where to report an issue :)

Comment (EnTeQuAk) [inline static/js/zamboni/files.js]: screenshot from 2017-02-06 18-40-17

with https://github.com/mozilla/addons-server/pull/4600/commits/3a2667ba02c4a13ead3fec899a9c9bc2297f3445

File: src/olympia/files/helpers.py (hunk 3 above)
Comment (EnTeQuAk) [inline src/olympia/files/helpers.py]: Fixed in https://github.com/mozilla/addons-server/pull/4600/commits/3a2667ba02c4a13ead3fec899a9c9bc2297f3445

File: static/js/zamboni/files.js (hunk 1 above)
Comment (EnTeQuAk) [inline static/js/zamboni/files.js]: Not super fancy looking but it does the job.

File: src/olympia/files/helpers.py (hunk 3 above)
Comment (wagnerand) [inline src/olympia/files/helpers.py]: I can't see the fix. 😕

File: src/olympia/files/templates/files/viewer.html [hunk 4]
```diff
@@ -18,6 +18,18 @@
      {% if automated_signing %}data-automated-signing="true"{% endif %}
      data-validation-failed="{{ _("Validation failed:") }}"></div>
 
+<div class="modal highlighter-output-broken js-hidde">
+  <h2>{{ _('File content not supported') }}</h2>
```
Comment (wagnerand) [inline src/olympia/files/templates/files/viewer.html]: I'm sorry for the extra round, but I think `File content display not supported` would be a bit more descriptive. Just a suggestion, though.

File: static/js/zamboni/files.js [hunk 5]
```diff
@@ -112,6 +112,32 @@ var Highlighter = {
...
+                if (aliases == null) {
+                    continue;
+                }
+
+                for (var i = 0, l = aliases.length; i < l; i++) {
+                    brushes.push(aliases[i]);
+                }
+            }
+
+            if (brushes.indexOf(brush.toLowerCase()) == -1) {
```
Comment (wagnerand) [inline static/js/zamboni/files.js]: We could use `Array.includes()` here 😉.

File: static/js/zamboni/files.js [hunk 6]
```diff
@@ -112,6 +112,32 @@ var Highlighter = {
...
+                $('.highlighter-output-broken').modal('', { width: 520 }).render();
```
Comment (wagnerand) [inline static/js/zamboni/files.js]: Let's make this a bit wider so, the header does not wrap for locales that generally use more characters per word, for example German :)

File: src/olympia/files/helpers.py (hunk 3 above)
Comment (EnTeQuAk) [inline src/olympia/files/helpers.py]: I had some fancy git/github issues yesterday, there we go: 572e3c8e05

File: src/olympia/files/templates/files/viewer.html [hunk 7]
```diff
@@ -18,6 +18,18 @@
      {% if automated_signing %}data-automated-signing="true"{% endif %}
      data-validation-failed="{{ _("Validation failed:") }}"></div>
 
+<div class="modal highlighter-output-broken js-hidde">
```
Comment (EnTeQuAk) [inline src/olympia/files/templates/files/viewer.html]: Nice catch, thanks! fixed in 88a29a7edb

File: static/js/zamboni/files.js (hunk 6 above)
Comment (EnTeQuAk) [inline static/js/zamboni/files.js]: Fixed in 4ab6e79c83

File: src/olympia/files/templates/files/viewer.html (hunk 4 above)
Comment (EnTeQuAk) [inline src/olympia/files/templates/files/viewer.html]: I went with `File content not supported for syntax highlighting` if that works?

File: static/js/zamboni/files.js [hunk 8]
```diff
@@ -112,6 +112,32 @@ var Highlighter = {
...
 
+        // Verify that we actually support the used brush
+        // see https://github.com/mozilla/addons-server/issues/4552 for more
+        // details. This shows an alert if a brush is not supported.
+        var discoveredBrushes = SyntaxHighlighter.brushes;
+
+        if (discoveredBrushes) {
+            var brushes = [];
+
+            for (var discoveredBrush in discoveredBrushes) {
```
Comment (EnTeQuAk) [inline static/js/zamboni/files.js]: We actually iterate only over non-integer properties in the array, unless I misunderstand you.

File: static/js/zamboni/files.js (hunk 5 above)
Comment (EnTeQuAk) [inline static/js/zamboni/files.js]: Fixed in 05c8c83968 :)

File: static/js/zamboni/files.js (hunk 8 above)
Comment (wagnerand) [inline static/js/zamboni/files.js]: Oh, you are right. My bad.
