### PR TITLE
Disable activity reply form submit during submission to avoid dupe replies

### LINKED ISSUE #4740: Empty replies can be performed for a version of an Add-on or of a WebExtension
### Describe the problem and steps to reproduce it:
Leave a reply with an empty field for any version from this WebExtension https://addons-dev.allizom.org/en-US/developers/addon/activitymail20/versions  

### What happened?
A reply with an empty field can be performed and an email is sent to the user.

### What did you expect to happen?
A warning for the empty field is displayed.

### Anything else we should know?
Verified on FF54.0a1 under Win 7 64-bit.
This issue is reproducing on -dev and stage servers.
Please see the video for this bug :
empty reply

### LINKED ISSUE #4900: Activity email: Clicking the 'Reply' button several times quickly send the message multiple times.
### Describe the problem and steps to reproduce it:

STR:
1. Go to an add-on version page on the devhub.
2. Open the review history panel.
3. Type something in the textbox.
4. Quickly click 'Reply' several times.

### What happened?

The message will be added several times.

### What did you expect to happen?

The message is only added once.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #4900 
fixes #4740

### CODE REVIEW

File: static/js/zamboni/devhub.js [hunk 1]
```diff
@@ -794,11 +794,16 @@ function initVersions() {
     $(".dev-review-reply-form").submit(function (e) {
         e.preventDefault();
         $replyForm = $(e.target)
+        if ($replyForm.children('textarea').val() == '') {
+            return false
+        }
+        submitButton = $replyForm.children('button')
```
Comment (wagnerand) [inline static/js/zamboni/devhub.js]: Let's make this a local var.

Comment (eviljeff) [inline static/js/zamboni/devhub.js]: https://github.com/mozilla/addons-server/pull/4905/commits/4e888ee60757926af7c1916441a295862e36e996
