### PR TITLE
Fix dates in stats export links (csv/json)

### LINKED ISSUE #14826: csv reports are generated within the chosen interval plus one extra day
From https://github.com/mozilla/addons-server/issues/14796#issuecomment-652378499

STR:
1. Go to an addon with stats such as https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/usage/?last=30
2. Generate a report with a custom date range  let's say 12.04.2020 - 05.06.2020 and export it in .csv format. 
3. Open the report and observe the intervals.

Actual result:
 the csv report is generated with an extra day 12.04 -06.06 and if 06.06 has data this is displayed too. 

Expected:
report should be for 12.04.2020 - 05.06.2020

Notes:
That's reproducible for both beta and legacy - FF77(win10).

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #14826 

---

This patch also includes some JS tests. Things would be a bit better if we could use ES6 in our source files.

### CODE REVIEW

File: static/js/impala/stats/stats.js [hunk 1]
```diff
@@ -1,104 +1,122 @@
...
+      baseURL = $('.primary').attr('data-base_url');
+
+    $(window).on('changeview', function (e, newView) {
+      _.extend(view, newView);
+      var metric = view.metric;
+
+      var range = normalizeRange(view.range);
+
+      // See: https://github.com/mozilla/zamboni/commit/4263102
+      if (
```
Comment (willdurand) [inline static/js/impala/stats/stats.js:85]: The actual fix is this `if`.

File: static/js/impala/stats/helpers.js [hunk 2]
```diff
@@ -29,7 +29,7 @@ function WorkerPool(size) {
                 worker.addEventListener('message', function(e) {
                     if (job.cb.call(job.ctx, e.data, worker)) {
                         worker.terminate();
-                        delete worker;
+                        worker = null;
```
Comment (willdurand) [inline static/js/impala/stats/helpers.js:32]: We can't `delete` in strict mode.

**Comment by willdurand** [comment]
I'm going to see if I can reproduce/fix https://github.com/mozilla/addons-server/issues/12052 with this test suite. If that's the case, this test suite would be very useful. If not, well it's less useful but still interesting because we could at least execute the code once in Travis.

File: tests/js/zamboni/stats.spec.js [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+    dateMock.clear();
+  });
+
+  describe('stats/stats.js', () => {
+    const report = 'apps';
+
+    let stats_stats;
+
+    beforeEach(() => {
+      stats_stats = require('../../../static/js/zamboni/stats-all.js')
```
Comment (willdurand) [inline tests/js/zamboni/stats.spec.js:38]: Using the compiled (or just concatenated?) version is easier because of the various dependencies. Fortunately, all deps are not global. We could use the minified version but that makes reading errors tricky.

Comment (willdurand) [reply tests/js/zamboni/stats.spec.js:38]: It needs to be `require`'ed that way because of the few global mocks declared above.

**Comment by willdurand** [comment]
@diox updated the patch to use the `assets` toxenv
