### PR TITLE
Fix 'Clear Admin Static Theme Review Flag' button

### LINKED ISSUE #14523: Clearing theme admin review flag does not work
### Describe the problem and steps to reproduce it:

1. Have a theme that is pending admin review
2. Click _Clear Admin Static Theme Review Flag_ at the bottom of the review page

### What happened?

Nothing

### What did you expect to happen?

The flag should be unset and the button should disappear.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

### PR DESCRIPTION
**Pull request by wagnerand**
Fix #14523.

### CODE REVIEW

File: static/js/zamboni/reviewers.js [hunk 1]
```diff
@@ -222,7 +222,7 @@ function initExtraReviewActions() {
     }));
 
     // One-off-style buttons.
-    $('#clear_admin_code_review, #clear_admin_content_review, #clear_pending_info_request, #clear_auto_approval_delayed_until').click(_pd(function() {
+    $('#clear_admin_code_review, #clear_admin_content_review, #clear_admin_theme_review, #clear_pending_info_request, #clear_auto_approval_delayed_until').click(_pd(function() {
```
Comment (eviljeff) [inline static/js/zamboni/reviewers.js:225]: ugh, this is not a good coding pattern.  They should have a common class instead.

Comment (diox) [reply static/js/zamboni/reviewers.js:225]: Yeah that one is my fault, it started with just a couple buttons and grew...
