### PR TITLE
Fixes #1011: Don't show 'Your submission will be automatically signed…

### LINKED ISSUE #1011: Don't show 'Your submission will be automatically signed.' for add-on types we don't sign
## steps to reproduce:
1. Load https://addons.allizom.org/en-US/developers/addon/submit/2
2. Upload a search tool as an unlisted add-on
## observed behavior:

A developer who doesn't know that only extensions get signed may be confused by our validation message which says "Your submission will be automatically signed." even for search tools.
## screenshot:

https://www.dropbox.com/s/smcrv7jf5vg3von/Screenshot%202015-12-01%2013.16.23.png?dl=0

### PR DESCRIPTION
**Pull request by lavish205**
….' for add-on types we don't sign
#1011

### CODE REVIEW

File: static/js/common/upload-addon.js [hunk 1]
```diff
@@ -429,7 +429,8 @@
                     $("<strong>").text(message).appendTo(upload_results);
 
                     // Specific messages for unlisted addons.
-                    if (isUnlisted()) {
+                    var validation_type = results.validation.detected_type
+                    if ((validation_type == 'extension' || validation_type == 'dictionary' || validation_type == 'languagepack') && isUnlisted()) {
```
Comment (eviljeff) [inline static/js/common/upload-addon.js]: You can do `if (["extension", "dictionary", "languagepack"].includes(validation_type) && isUnlisted())` (I think 😆 - my javascript is really rusty)
We generally use double quotes `"` in our javascript, by convention.

Comment (lavish205) [inline static/js/common/upload-addon.js]: ok I'll update this

File: static/js/common/upload-addon.js [hunk 2]
```diff
@@ -429,7 +429,8 @@
                     $("<strong>").text(message).appendTo(upload_results);
 
                     // Specific messages for unlisted addons.
-                    if (isUnlisted()) {
+                    var validation_type = results.validation.detected_type
+                    if (["extension", "dictionary", "languagepack"].includes(validation_type) && isUnlisted()) {
```
Comment (eviljeff) [inline static/js/common/upload-addon.js]: because `.includes` is quite a new addition to JavaScript can you change to use `.indexOf` instead?  Sorry!

File: static/js/common/upload-addon.js [hunk 3]
```diff
@@ -429,7 +429,8 @@
                     $("<strong>").text(message).appendTo(upload_results);
 
                     // Specific messages for unlisted addons.
-                    if (isUnlisted()) {
+                    var validation_type = results.validation.detected_type
+                    if (["extension", "dictionary", "languagepack"].indexOf(validation_type) && isUnlisted()) {
```
Comment (eviljeff) [inline static/js/common/upload-addon.js]: `.indexOf` returns an index or `-1` if not in the list (what's written would test if validation_type wasn't "extension", because that's index=0, so would be true for not in the list or index=1 or index=2).  
`["extension", "dictionary", "languagepack"].indexOf(validation_type) != -1`

**Comment by caitmuenster** [comment]
Thanks @lavish205!
