### PR TITLE
FIxed Issue: #2979 Delete RereviewQueue model

### LINKED ISSUE #2979: Delete "RereviewQueue" model
This model was intended for apps, which never really happened.

The model and the according database table "rereview_queue" should be deleted.

### PR DESCRIPTION
**Pull request by lavish205**
Fixes #2979

### CODE REVIEW

File: src/olympia/migrations/881-remove-rereview-table.sql [hunk 1]
```diff
@@ -0,0 +1 @@
+DROP TABLE rereview_queue;
```
Comment (EnTeQuAk) [inline src/olympia/migrations/881-remove-rereview-table.sql]: Just for safety reasons, could we please use `DROP TABLE IF EXISTS`?

**Comment by EnTeQuAk** [comment]
It's a bit sad that no tests fail but it realls is not used anywhere or even imported. Looks good, just minor change I'd love to see and we can merge that.

Thanks! :smiley:

**Comment by EnTeQuAk** [comment]
Awesome, thanks for the update! :cake: :beers: :star2: :smiley:
