### PR TITLE
toolbar elements should fallback to textcolor if toolbar_text not set

### LINKED ISSUE #9616: [static-themes] colors.tab_selected property not previewed
Originally filed by @nt1m here https://github.com/mozilla/addons-frontend/issues/6535

### Describe the problem and steps to reproduce it:
- colors.tab_selected changes the background of the selected tab.
Example: https://addons.mozilla.org/en-US/firefox/addon/devfox/

### What happened?

Selected tab has same background as toolbar

### What did you expect to happen?

Selected tab should have blue background distinct from the toolbar

### LINKED ISSUE #9642: Theme 'textcolor' is applied to toolbar text and icons in the browser while AMO preview is represented differently
STR:

1. Log in to AMO 
2. Submit a new theme through the wizard
3. Select a value for "Header area text and icons" and leave the other fields to their default status
4. Observe the generated preview after the theme is submitted
5. Approve and install the theme
6. Compare the preview with the installed version

Actual result:
In the browser, the selected `textcolor` is also applied to toolbar area text and icons

Expected result:
AMO theme preview should match with the theme applied in the browser

Notes:
- I'm inclined to believe that this is an issue with how Firefox is displaying the theme, but I wasn't completely sure
- reproduced on all AMO servers with FF62, 60 ESR and Nightly 64, Win10x64

image

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #9642  + fixes #9616 now too

### CODE REVIEW

File: static/js/zamboni/static_theme.js [hunk 1]
```diff
@@ -134,13 +134,18 @@ $(document).ready(function() {
         var $color = $wizard.find('input.color-picker');
         $color.change(function() {
             var $this = $(this),
-                $svg_element = $('.' + $this[0].id);
+                color_class = '.' + $this[0].id,
```
Comment (diox) [inline static/js/zamboni/static_theme.js]: Need a `var`. Also, maybe call this `color_property_selector` or something similar instead instead: since it includes the `.` it's not technically a class name, and well, not technically just a color either :)

Comment (eviljeff) [reply static/js/zamboni/static_theme.js]: it's in the var - see the `,` on the line above.  I'll rename.

Comment (eviljeff) [reply static/js/zamboni/static_theme.js]: https://github.com/mozilla/addons-server/pull/9859/commits/c5609381e7cfe6c168adedaabdbb793947a0bfe6

Comment (diox) [reply static/js/zamboni/static_theme.js]: Oh yeah, damn multi-line declarations
