### PR TITLE
Fixes #3098. 

### LINKED ISSUE #3098: Confirmation message is displayed even when the changes are not saved
Steps to reproduce:

1.Load My Submissions page https://addons.allizom.org/en-US/developers/addons 
2.Open an add-on Edit Listing page, click Edit button from the right side of Support Information field.
3.Type an invalid URL and press “Save Changes” button. 

Expected results:
Website field should display a warning message, the confirmation message is not displayed.

Actual results:
A confirmation message is displayed next to “Support Information” even if the changes are not saved.

Note/Issues:
Verified on FF50.0a1 (2016-07-13) (Win 7 64-bit)
This issue is reproducing in AMO -dev, stage and production servers
Here is a video for this issue:
test

### PR DESCRIPTION
**Pull request by rafspiny**
Attempt to address the issue with saved message being displayed when edit errors occur. Fix #3098

The change regards the object on which we search for HTML elements with the class **errorList**, in order to be retrieve all possible errors that happened once the form has been submitted.

There were no tests about this that I could find.

Here is a screenrecording of how the UI changed
addons-server-3098-fix

Let me know if this is an acceptable solution.

### CODE REVIEW

File: static/js/zamboni/devhub.js [hunk 1]
```diff
@@ -335,11 +335,11 @@ function addonFormSubmit() {
             parent_div.find(".item").removeClass("loaded").addClass("loading");
             var $document = $(document),
                 scrollBottom = $document.height() - $document.scrollTop(),
-                $form = $(this),
-                hasErrors = $form.find('.errorlist').length;
+                $form = $(this);
 
             $.post($form.attr('action'), $form.serialize(), function(d) {
                 parent_div.html(d).each(addonFormSubmit);
+                hasErrors = parent_div.find('.errorlist').length;
```
Comment (diox) [inline static/js/zamboni/devhub.js]: Nice, well spotted. So, your change does fix the issue, but I think we should write all this more defensively. Can you try doing the following:
1. In the beginning of the function, do `$form = parent_div.find('form');`. Add a comment explaining that we need to do that because we just changed the whole html of the parent div.
2. When assigning `hasErrors` like you did, add a `var` to make sure it's not global and keep using the same assignation as before, `$form.find('.errorlist').length;`. Now that `$form` has been updated and we are in the function it should work, and be slightly more reliable

Comment (rafspiny) [reply static/js/zamboni/devhub.js]: Thanks for the hints. I just pushed a commit addressing your comments.

File: static/js/zamboni/devhub.js [hunk 2]
```diff
@@ -335,11 +335,13 @@ function addonFormSubmit() {
             parent_div.find(".item").removeClass("loaded").addClass("loading");
             var $document = $(document),
                 scrollBottom = $document.height() - $document.scrollTop(),
-                $form = $(this),
-                hasErrors = $form.find('.errorlist').length;
+                $form = $(this);
 
             $.post($form.attr('action'), $form.serialize(), function(d) {
+                // The HTML has changed after we posted the form, thus the need to retrieve the new HTML
```
Comment (diox) [inline static/js/zamboni/devhub.js]: Can you move that comment one line down ? Since that's the line below that changes the HTML.

Comment (rafspiny) [reply static/js/zamboni/devhub.js]: Done.

**Comment by diox** [comment]
Thanks, @rafspiny !
