### PR TITLE
Convert UserProfile's addon average rating to float to match other models

### LINKED ISSUE #7822: average_addon_rating is returned as a string, not a float
### Describe the problem and steps to reproduce it:
The API returns the prop on a `User` response's `average_addon_rating` as a string but really it should be a float. I'd be great if this was set properly from the API, as right now it causes us to have to locally typecast it.

### PR DESCRIPTION
**Pull request by diox**
Fix #7822 again (the API uses a `FloatField` already, the patch that did that was only reverted in the tag, not master)

### CODE REVIEW

File: src/olympia/migrations/1005-convert-average-rating-to-float.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+-- Before converting to a double, get rid of the empty string values we can't
+-- convert.
+UPDATE users SET averagerating=NULL WHERE averagerating = "";
+-- Make it a double.
+ALTER TABLE users MODIFY averagerating double;
```
Comment (eviljeff) [inline src/olympia/migrations/1005-convert-average-rating-to-float.sql]: I'm actually kind of impressed mysql/mariadb can do that conversion without blowing up

Comment (diox) [reply src/olympia/migrations/1005-convert-average-rating-to-float.sql]: Yeah, me too. It does blow up on empty strings, but works fine with `NULL` and floats-as-strings.

**Comment by diox** [comment]
I'll fix the task (which amusingly seems to work anyway, but that's ugly)
