### PR TITLE
Fix file tree when accessing binary files

### LINKED ISSUE #2226: File tree sometimes not being correctly loaded in editor tools
The file tree is not being correctly loaded when visiting https://addons.mozilla.org/en-US/firefox/files/browse/421089/file/data/html/images/themes/default/inspector/UIComponents/VolumeBar.png#top. If you go to https://addons.mozilla.org/en-US/firefox/files/browse/421089/ and then navigate to the file, then the tree is shown correctly.

I found this in combination with mozilla/amo-validator#411 where that specific file is wrongfully considered to have a flagged extension.

### PR DESCRIPTION
**Pull request by wagnerand**
Fixes #2226

### CODE REVIEW

File: static/js/zamboni/files.js [hunk 1]
```diff
@@ -330,7 +330,10 @@ function bind_viewer(nodes) {
         this.top = null;
         this.last = null;
         this.compute = function(node) {
-            Highlighter.highlight(node.find('#diff, #content'));
+            let content = node.find('#diff, #content');
+            if (content.length) {
+                Highlighter.highlight(content);
+            }
```
Comment (wagnerand) [inline static/js/zamboni/files.js]: Bonus: This fixes a JavaScript error in `highlight.js` when accessing binary files.

**Comment by tofumatt** [comment]
Seems fine to me; I don't know this code well but r+ from me.

**Comment by wagnerand** [comment]
Thank you!
