### PR TITLE
move from media_url to static_url

### LINKED ISSUE #1883: Example links from manage payments page are not working
**Steps to reproduce:**
1. Open manage payments page for an add-on that has payments set up i.e: https://addons.allizom.org/en-US/developers/addon/adblock-plus/payments
2. Scroll down to "When should users be asked for contributions?" section and click on one of the "example" links.

**Expected results:**
The example page/image is displayed.

**Actual results:**
Nothing happens.

**Notes/Issues:**
Verified in FF45(Win7) Issue can be reproduced in -dev and stage.
Screencast for this issue: http://screencast.com/t/9R5vjHIZ

### PR DESCRIPTION
**Pull request by andymckay**
Fixes #1883 

* they were using a url of /user-media/ instead of /static/ so this moves them over to static:
https://addons.cdn.mozilla.net/static/img/zamboni/contributions/passive.png
* they are so old they do make me cringe a little...

### CODE REVIEW

File: static/js/zamboni/devhub.js [hunk 1]
```diff
@@ -787,7 +787,7 @@ function initPayments(delegate) {
         "img/zamboni/contributions/after.png",
         "img/zamboni/contributions/roadblock.png",
     ],
-        media_url = $("body").attr("data-media-url"),
+        static_url = $("body").attr("data-static-url"),
         to = false,
         img = $("<img id='contribution-preview' alt='' />");
         moz = $("input[value='moz']");
```
Comment (muffinresearch) [inline static/js/zamboni/devhub.js]: Not your code but my lint-sense is tingling - this looks like it might be global since the previous line has a ';'

**Comment by muffinresearch** [comment]
r+wc

File: static/js/zamboni/devhub.js (hunk 1 above)
Comment (muffinresearch) [inline static/js/zamboni/devhub.js]: Might be worth moving to a var per line since we're in here?

Comment (andymckay) [inline static/js/zamboni/devhub.js]: That's a var, because the previous line is a , - but I'll note line 792 ends in a ; , meaning 793 is a global. I can change it to be a var per line.

Comment (muffinresearch) [inline static/js/zamboni/devhub.js]: Yep that's the line I'm referring to (the comment is about line 793)
