### PR TITLE
Only show download anyway button for incompatible add-ons, force download

### LINKED ISSUE #6212: Compatible add-ons have "Download anyway" link
Steps to reproduce:
1. Load details page to a compatible with your browser add-on i.e. https://addons-dev.allizom.org/en-US/firefox/addon/webext-simple/?src=search or https://addons-dev.allizom.org/en-US/firefox/addon/firebug/?src=search

Expected results:
There is a green installation button.

Actual results:
There is a "Download anyway" link under the installation button.

Notes/Issues:
- reproducing for compatible extensions and webextensions
Verified on FF55(Win 7). Reproducing only on dev.
Screenshot for this issue:
webext

### PR DESCRIPTION
**Pull request by diox**
Fix #6212

### CODE REVIEW

File: static/js/zamboni/buttons.js [hunk 1]
```diff
@@ -179,16 +178,28 @@ var installButton = function() {
...
+            var href = $button.filter(':visible').attr('href');
+            var pos = href.lastIndexOf('/');
+            href = escape_(href.slice(0, pos) + '/type:attachment/' + href.slice(pos + 1));
+            var $newParent = $installShell.find('.more-versions');
+            $newParent.append(' | ');
+            $newParent.append($downloadAnyway);
+            $downloadAnyway.attr('href', href);
+            $downloadAnyway.show();
+        }
+    }
```
Comment (EnTeQuAk) [inline static/js/zamboni/buttons.js]: Can you maybe post a screenshot how this is supposed to look for QA to check as well?

File: static/js/zamboni/buttons.js [hunk 2]
```diff
@@ -179,16 +178,28 @@ var installButton = function() {
         };
     });
 
+    var showDownloadAnyway = function($button) {
+        var $installShell = $button.parents('.install-shell');
+        var $downloadAnyway = $installShell.find('.download-anyway');
+        if ($downloadAnyway.length) {
+            var href = $button.filter(':visible').attr('href');
+            var pos = href.lastIndexOf('/');
+            href = escape_(href.slice(0, pos) + '/type:attachment/' + href.slice(pos + 1));
```
Comment (EnTeQuAk) [inline static/js/zamboni/buttons.js]: I really don't have a better alternative but this essentially transforms `/firefox/downloads/latest/privacy-badger17/platform:2/addon-506646-latest.xpi` into `/firefox/downloads/latest/privacy-badger17/platform:2/type:attachment/addon-506646-latest.xpi` right?

Comment (EnTeQuAk) [inline static/js/zamboni/buttons.js]: Just verified in console, this looks properly and seems to work.

Comment (EnTeQuAk) [inline static/js/zamboni/buttons.js]: This might not work, our regular expression in `versions.urls` expects `type` to come before `platform` and this does the reverse. Unless this is a `file/:id/` link?

Comment (diox) [inline static/js/zamboni/buttons.js]: It should be the `downloads.latest` URL, but I forgot platforms... I'll check locally with multi-platforms add-ons.

Comment (diox) [inline static/js/zamboni/buttons.js]: Yeah, it's broken in that scenario, so I need to think of a better way... I originally developed this thinking it would be using `downloads.file`, which does not have the platform bit, but since it's using `downloads.latest` which does, I need to rehink this... Maybe I can reverse the URL with `'type': 'attachment'` set and pass it all the way down to the JavaScript.

Comment (diox) [inline static/js/zamboni/buttons.js]: Pushed an attempt to do this in 2c1b312352d89ba8cb994eb0028beece4b937dcf
