### PR TITLE
Fix autocomplete widget for collections edition

### LINKED ISSUE #1626: Can't add a new add-on to the featured collection
When trying to add a new add-on to the featured collection (using [this link](https://addons.mozilla.org/en-US/firefox/collections/mozilla/featured-add-ons/edit/#addons-edit)), there's a js error in the console, which prevents doing it:
```
TypeError: this._renderItem(...) is undefined
._renderItemData() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
._renderMenu/<() common-min.js:3
.each() preload-min.js:1
._renderMenu() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
._suggest() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
.__response() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
e.widget/</l[t]</r() common-min.js:2
.__response() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
._response/<() common-min.js:3
.proxy/i() preload-min.js:1
n() common-min.js:1
p.Callbacks/u() preload-min.js:1
p.Callbacks/l.fireWith() preload-min.js:1
k() preload-min.js:3
.send/n() preload-min.js:3
```

Maybe an issue with the js bundle that doesn't include static/js/impala/formset.js?

### PR DESCRIPTION
**Pull request by magopian**
Fixes #1626

### CODE REVIEW

File: static/js/zamboni/collections.js [hunk 1]
```diff
@@ -268,6 +268,8 @@ if (addon_ac.length) {
                 .data('item.autocomplete', item)
                 .append('<a><img src="' + item.icons['32'] + '" alt="">' + _.escape(item.name) + '</a>')
                 .appendTo(ul);
+        } else {
+            return ul;
```
Comment (muffinresearch) [inline static/js/zamboni/collections.js]: Does `_renderItem` ignore the ul returned here - seems weird since the bit in the if block is actually returning the li.

Comment (magopian) [inline static/js/zamboni/collections.js]: Ah, I thought `.appendTo(ul)` was returning the `ul`. I'm changing this line to `return $('<li>')`.

This current code works well locally though, which is odd.

**Comment by EnTeQuAk** [comment]
r+
