### PR TITLE
Don't open new tab for false positive scanner result report

### LINKED ISSUE #20260: Don't open new tab when reporting a scanner result as false positive
### Describe the problem and steps to reproduce it:

1. Have a submission being flagged by a scanner.
2. On a scanner result page in django admin, click "False positive" for a result.

### What happened?

The same page opens in a new tab.

### What did you expect to happen?

No new tab should be opened (and the report should still be applied correctly).

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

### PR DESCRIPTION
**Pull request by wagnerand**
Fix #20260.

### CODE REVIEW

File: static/js/scanners/scannerresult_actions.js [hunk 1]
```diff
@@ -1,7 +0,0 @@
-document.querySelectorAll('.report-false-positive-button').forEach((button) => {
-  button.addEventListener('click', () => {
-    setTimeout(() => {
-      window.location.reload();
```
Comment (eviljeff) [inline static/js/scanners/scannerresult_actions.js:4]: I've not reviewed this code before, but isn't this js to allow the page to reflect the updated result?  Is that not needed now too?  (the issue didn't mention about page reloads)

Comment (wagnerand) [reply static/js/scanners/scannerresult_actions.js:4]: The patch is changing the form target from "_blank" (opening a new tab) "_self"  (default, unspecified), which will cause the original tab to be reloaded.

**Review by eviljeff — APPROVED** [review]
