### PR TITLE
Remove the "login_attempt" columns from the users table now that they are no longer used

### LINKED ISSUE #9117: Remove last_login_attempt, failed_login_attempts, last_login_attempt_ip
The login attempt fields (`last_login_attempt`, `failed_login_attempts`, `last_login_attempt_ip`) were used to log information about login attempts, failed or successful. With the switch to Firefox Accounts though, we never get information about this anymore - FxA does.

That means those fields are obsolete. And indeed, the method filling them, `log_login_attempt()`, accepts a `successful` parameter but it's never set to `False`.

For #7333 I'm probably going to replace the method entirely, and make the fields nullable. We'll then be able to remove the fields entirely in a follow-up push.

### PR DESCRIPTION
**Pull request by diox**
Fix #9117

### CODE REVIEW

File: src/olympia/migrations/1044-remove-login-attempt-fields.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+-- Those fields were NULLed and removed from the model earlier, they are no longer used.
+ALTER TABLE `users` DROP COLUMN `last_login_attempt_ip`, DROP COLUMN `failed_login_attempts`, DROP COLUMN `last_login_attempt`;
```
Comment (EnTeQuAk) [inline src/olympia/migrations/1044-remove-login-attempt-fields.sql]: Can we put the `DROP COLUMN` entries on separate lines?

File: src/olympia/migrations/1044-remove-login-attempt-fields.sql [hunk 2]
```diff
@@ -0,0 +1,2 @@
+-- Those fields were NULLed and removed from the model earlier, they are no longer used.
```
Comment (EnTeQuAk) [inline src/olympia/migrations/1044-remove-login-attempt-fields.sql]: it may make sense to link to the PR where that happened
